### ISSUE TITLE
lines with extra tabs makes the program consume large amount of memory

### ISSUE THREAD

**Issue by lemredd** [KennethTrecy/chearmyp_lexer#1]
Since chearmyp parser is being used in pruecendrae to parse configuration files, and run several scripts at once, but sometimes the program overflows and crashes.

With the help of the author, we initially figured out the root of the problem. Lines with extra tabs may have caused the crash.

It would be great if chearmyp would show any redundant spaces and tabs when the configuration runs.

**Comment by KennethTrecy** [comment]
After creating a test, the error was found in the lexer. See the test [09ed703](https://github.com/KennethTrecy/chearmyp_lexer/commit/09ed70323829b4c13193c337610314301e110394).

**Comment by KennethTrecy** [comment]
Found another instance for inner empty scopes. See [test] in commit e221c7e.

[test]: https://github.com/KennethTrecy/chearmyp_lexer/blob/e221c7ed9fe46d613c3b5721088ff14191a10725/src/secondary_lexers/lex.rs#L207
